In [4]:
import pandas as pd

In [5]:
data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]

In [7]:
pd.DataFrame(data)

         0   1
0    Alice  25
1      Bob  30
2  Charlie  35

In [19]:
import numpy as np
df = np.array([[10, 20, 30], [40, 50, 60]])
pd.DataFrame(df)

    0   1   2
0  10  20  30
1  40  50  60

In [18]:
import numpy as np
df = np.array([[10, 20, 30], [40, 50, 60]])
pd.DataFrame(df, columns = ["A", "B", "C"])

    A   B   C
0  10  20  30
1  40  50  60

In [16]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

df = pd.DataFrame(data)
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [23]:
pd.read_excel("data.xlsx")

                  Name         Role
0          Virat Kohli      Batsman
1          Venky Iyyer      Batsman
2     Devdutt Padikkal      Batsman
3        Rajat Patidar      Batsman
4            Tim David      Batsman
5        Jitesh Sharma   WK-Batsman
6      Romario Sheferd  All-Rounder
7        Krunal Pandya  All-Rounder
8   Bhuvaneshwar Kumar       Bowler
9       Josh Hazelwood       Bowler
10    Rasikh Dar Salam       Bowler

In [30]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [31]:
df.head()         # First 5 rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [32]:

df.info()         # Column info: types, non-null

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 17.3 KB

In [33]:
df.describe()     # Stats for numeric columns

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000