In [1]:
import pandas as pd

In [9]:
df = pd.read_csv("data_cleaning.csv")

In [10]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [4]:
df.sort_values("Age")

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [5]:
df.sort_values("Age", ascending = False)

      Name   Age         City Gender              Email   Join Date
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [17]:
df2 = df.drop_duplicates().dropna()

In [22]:
df2.sort_values(["Name", "Age"])

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019

In [28]:
df2.sort_values("Age")

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020

In [29]:
df2.reset_index(drop=True)  # Reset the index and drop the old index

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.0       Mumbai      M  david@example.com  12-11-2019

In [32]:
# df2["Rank"] = df["Age"].rank()

In [33]:
df2

      Name   Age         City Gender              Email   Join Date  Rank
0    Alice  25.0     New York      F  alice@example.com  01-05-2021   3.5
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021   3.5
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   7.0
4    David  22.0       Mumbai      M  david@example.com  12-11-2019   1.0

In [34]:
df2["Rank"] = df2["Age"].rank(method="dense")

In [35]:
df2

      Name   Age         City Gender              Email   Join Date  Rank
0    Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021   2.0
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   3.0
4    David  22.0       Mumbai      M  david@example.com  12-11-2019   1.0

In [38]:
df2.rename(index={0: "row1", 1: "row2"})

         Name   Age         City Gender              Email   Join Date  Rank
row1    Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
row2  Charlie  25.0        Delhi      M    charlie@example  20-07-2021   2.0
2         Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   3.0
4       David  22.0       Mumbai      M  david@example.com  12-11-2019   1.0

In [39]:
df2

         Name   Age         City Gender              Email   Join Date  Rank
row1    Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
row2  Charlie  25.0        Delhi      M    charlie@example  20-07-2021   2.0
2         Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   3.0
4       David  22.0       Mumbai      M  david@example.com  12-11-2019   1.0

In [41]:
cols = ["Email"] + [col for col in df2.columns if col != "Email"]
df2 = df2[cols]

In [42]:
df2

                  Email     Name   Age         City Gender   Join Date  Rank
row1  alice@example.com    Alice  25.0     New York      F  01-05-2021   2.0
row2    charlie@example  Charlie  25.0        Delhi      M  20-07-2021   2.0
2       bob@example.com      Bob  30.0  Los Angeles      M  15-06-2020   3.0
4     david@example.com    David  22.0       Mumbai      M  12-11-2019   1.0